In [10]:
import pandas as pd
import numpy as np

In [11]:
games_genres = pd.read_csv('../data/raw/csv/Games_Genres.csv')
games_genres.head()

   appid   Genre
0     10  Action
1     20  Action
2     30  Action
3     40  Action
4     50  Action

# OneHotEncoding genres
Join all rows together by first changing the numbers to strings, then replacing '0' with '', group by 'appid' and finally join them in an aggregation

In [13]:
# Turn into categorical vectors and combine all genres for each appid into one row
games_cat = pd.Categorical(games_genres['Genre'])
cat_dum = pd.get_dummies(games_cat, prefix='Genre').astype(str)
cat_dum = pd.concat([games_genres, cat_dum], axis=1).drop('Genre', axis=1)
cat_dum.head()

,appid,Genre_Accounting,Genre_Action,Genre_Adventure,Genre_Animation & Modeling,Genre_Audio Production,Genre_Casual,Genre_Design & Illustration,Genre_Early Access,Genre_Education,...,Genre_Photo Editing,Genre_RPG,Genre_Racing,Genre_Simulation,Genre_Software Training,Genre_Sports,Genre_Strategy,Genre_Utilities,Genre_Video Production,Genre_Web Publishing
0,10,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,20,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,30,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,40,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,50,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [15]:
maybe = cat_dum.replace('0', '').groupby('appid', as_index=False).agg(''.join)
ohe_genres = maybe.replace('', '0').astype(int)
ohe_genres.to_csv('../data/processed/export/games_genres_ohe.csv', index=False)

ValueError: invalid literal for int() with base 10: 'appidGenre_AccountingGenre_ActionGenre_AdventureGenre_Animation & ModelingGenre_Audio ProductionGenre_CasualGenre_Design & IllustrationGenre_Early AccessGenre_EducationGenre_Free to PlayGenre_IndieGe

# Earlier attempt at joining multiple rows of genres per game into one

In [5]:
df = games_genres.groupby('appid')['Genre'].apply('|'.join).to_frame()

In [6]:
df.head(30)

                              Genre
appid
10                           Action
20                           Action
30                           Action
40                           Action
50                           Action
60                           Action
70                           Action
80                           Action
100                          Action
130                          Action
219                          Action
220                          Action
240                          Action
280                          Action
300                          Action
320                          Action
340                          Action
360                          Action
380                          Action
400                          Action
410                          Action
420                          Action
440             Action|Free to Play
500                          Action
550                          Action
570    Action|Free to Play|Strategy
620                Action|Adventure
630                          Action
659                Action|Adventure
730                          Action

In [7]:
df.to_csv('../data/processed/genres_text.csv')

In [23]:
df = pd.Categorical(df)
df.head()
#df_dummies = pd.get_dummies(df, prefix = 'Genre')
#df_dummies.head()

AttributeError: 'Categorical' object has no attribute 'head'

In [ ]:
steam_data['Genre'] = pd.Categorical(steam_data['Genre'])
steam_dummies = pd.get_dummies(steam_data['Genre'], prefix = 'Genre')
steam_df = pd.concat([steam_data, steam_dummies], axis=1)
steam_df.head()